apiVersion: v1
kind: Pod
metadata:
  name: serverweb5
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: serverweb6
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
