apiVersion: v1
kind: Secret
metadata:
  name: connectiondb
type: Opaque
stringData:
  host: localhost
  username: shidalgo
  password: '12345'
---
apiVersion: v1
kind: Pod
metadata:
  name: podnginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: connectiondb
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: connectiondb
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: connectiondb
              key: password
      volumeMounts:
        - name: test-vol
          mountPath: /opt
          readOnly: true
  volumes:
    - name: test-vol
      secret:
        secretName: connectiondb
        items:
          - key: username
            path: user.txt
