version: '3'

services:
  frontend:
    image: localhost:5000/frontend
    build:
      dockerfile: frontend/Dockerfile
      context: .
    ports:
      - 9000:3000
    environment:
      - PORT=3000
      - SERVICE_API1_ENDPOINT=http://localhost:9010/api
    networks:
      - ms-network

  backend1:
    image: localhost:5000/backend1
    build:
      dockerfile: backend1/Dockerfile
      context: .
    ports:
      - 9010:3010
    environment:
      - PORT=3010
      - SERVICE_API2_ENDPOINT=http://backend2:3020/api
    networks:
      - ms-network

  backend2:
    image: localhost:5000/backend2
    build:
      dockerfile: backend2/Dockerfile
      context: .
    environment:
      - PORT=3020
    networks:
      - ms-network

networks:
  ms-network:
